version: '3.8'
services:
  database-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=fsn
      - MYSQL_ROOT_PASSWORD=Haivan123
    ports:
      - '3307:3306'
    expose:
    - 3306

  backend:
    build: 
      context: ../api
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=database-mysql   
    ports:
      - '8000:8000'

# docker compose -p fsn-nodejs-mysql up -d